export const UI_STRINGS = {
  STREETS: {
    "3rd": "3rd",
    "4th": "4th",
    "5th": "5th",
    "6th": "6th",
    "7th": "7th",
  },
  ACTIONS: {
    BRING_IN: "Bring In",
    COMPLETE: "Complete",
    BET: "Bet",
    RAISE: "Raise",
    CALL: "Call",
    CHECK: "Check",
    FOLD: "Fold",
  },
  STAKES: {
    ANTE: "Ante",
    BRING_IN: "Bring In",
    SMALL_BET: "Small Bet (comp)",
    BIG_BET: "Big Bet",
  },
  GAMES: {
    studHi: "Stud Hi",
    razz: "Razz",
    stud8: "Stud Hi/Lo",
  },
  HAND_RANKS: {
    HIGH_CARD: "ハイカード",
    ONE_PAIR: "ワンペア",
    TWO_PAIR: "ツーペア",
    THREE_OF_A_KIND: "スリーカード",
    STRAIGHT: "ストレート",
    FLUSH: "フラッシュ",
    FULL_HOUSE: "フルハウス",
    FOUR_OF_A_KIND: "フォーカード",
    STRAIGHT_FLUSH: "ストレートフラッシュ",
  },
  COMMON: {
    WINNER: "勝者",
    POT: "ポット",
    NO_LOW: "ローなし",
    PLAYER_DEFAULT: (idx: number) => `Player ${idx}`,
    SEAT_DEFAULT: (idx: number) => `Seat ${idx}`,
  },
  SETUP: {
    TITLE: "Mix Poker MVP",
    SUBTITLE: "Setup your game",
    START_BUTTON: "Start Game",
  },
  PLAY: {
    START_NEW_DEAL: "Start New Deal",
    NO_GAME: "No game in progress",
    GO_TO_SETUP: "Go to Setup",
    NO_DEAL: "No deal available",
    ACTION_HISTORY_TITLE: (idx: number) => `アクション履歴 (#${idx})`,
  },
  DANGER_ZONE: {
    TITLE: "全データ削除",
    DESCRIPTION:
      "すべてのゲームデータ、履歴、お気に入りを削除します。この操作は取り消せません。",
    BUTTON_DELETE: "全データを削除",
    CONFIRM_PROMPT: "確認のため、以下を入力してください:",
    CONFIRM_TEXT: "DELETE ALL",
    BUTTON_EXECUTE: "削除を実行",
    BUTTON_CANCEL: "キャンセル",
  },
  MENU: {
    EXIT_GAME: "退出",
    CONFIRM_EXIT_GAME: "現在のゲームを終了して設定画面に戻りますか？",
  },
} as const;
